name: Ethio Ad Guard Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # በእጅህ "Run" ለማድረግ እንዲረዳህ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install aiogram==2.25.1

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
